### ISSUE TITLE
Discrepancy between the information content matrix and flanking sequences

### ISSUE THREAD

**Issue by snayfach** [Matteo-Ciciani/PAMpredict#5]
Hi Matteo,

I've noticed a discrepancy between the information content matrix and flanking sequences in certain cases. I've attached one such example.

Here's the information content from downstream_flanking_sequences_info.tsv:

pos | A | C | G | T
-- | -- | -- | -- | --
0 | 0.25 | 0.125 | 0.125 | 0
1 | 0.89154141 | 0 | 0.29718047 | 0
2 | 0.29718047 | 0 | 0.22288535 | 0.07429512
3 | 0.125 | 0.125 | 0 | 0.25
4 | 2 | 0 | 0 | 0
5 | 0 | 0.39208725 | 0 | 0.65347875
6 | 0 | 0.22288535 | 0.29718047 | 0.07429512
7 | 0.02359023 | 0.03538535 | 0.02359023 | 0.01179512
8 | 0.0707707 | 0.02359023 | 0.0707707 | 0.02359023
9 | 0.03538535 | 0.01179512 | 0.02359023 | 0.02359023

And here are the flanking sequences:

  | Upstream | Downstream
-- | -- | --
spacer_ERZ808262_210_7_1 | AGTGATATGGCAAGTTTCAATTCAGTGACG | GTCCGGCAGATAGGGGACAACAAGGTGGCG
spacer_ERZ808262_210_7_3 | CGCCTCCCGGATGGCCGGAAGGAGGTACTT | CGACTTCACGAACTTCTCGGAAGTCAGGAG
spacer_ERZ808262_210_7_4 | CTTGCCAAATTGGTGTCATATCTCGTTTTT | CCTCACCGCGCCCGTTCAAGCCGCCGCATC
spacer_ERZ808262_210_7_5 | CGCCGCACGGACTTCACGAACAGGATACTT | AGTGTCCCCCAATCGAGGAATGGCATGTAG
spacer_ERZ808262_210_7_6 | ATGACCACCGCCGCGCCTGCATGCATTTTT | AGACTTATTCCGAAACCCCATTTAGGCTGC
spacer_ERZ808262_210_7_11 | CCGCTTCAAGGACCCGGCGGCCCCATGCCC | GCGAATTTGCAAACTCTGCAAGGAGGAGGG
spacer_ERZ808262_210_7_15 | CGGAAGCAGGGCGGATAAAGACGCATATTG | GAGACGGTGGTATGATCAGATGAGCACGTC
spacer_ERZ808262_210_7_16 | AGGGAGTTGCCGTTGACGGTTTTGATATTC | TCTATTGCGGTTTGCAGAGCGTTGTCAGCC

From the matrix, adenine (A) is high information content at position 5 (index 4). But looking at the downstream sequences, A is not especially common at this position (2/8) or other positions. Do you have any explanation for the difference?

[2.fna.zip](https://github.com/Matteo-Ciciani/PAMpredict/files/11837754/2.fna.zip)

**Comment by Matteo-Ciciani** [comment]
Hi Stephen,

turns out both tables are correct and this difference is only the result of how spacer and PAM orientations are handled.

Flanking sequences in `consensus_flanking_sequences.tsv` are reported with respect to the input spacers. Information in the `_flanking_sequences_info.tsv` files are reported with respect to the spacer orientation inferred from PAM position. For Cas9 the expected PAM position is downstream, so if a consensus sequence is detected upstream (like in this case), it gets reverse complemented and it's reported in the expected orientation. You can check the inferred spacer orientation in `PAM_prediction.txt`: `Inferred input spacers orientation: Reverse.`

So in the matrix position 5 (index 4) refers to the reverse complement of the Upstream flanking sequence in `consensus_flanking_sequences.tsv`.

I'll update the output description to make this behavior more clear.

**Comment by snayfach** [comment]
Thanks for the explanation. As a side note, I've noticed that occasionally the program predicts the wrong strand when the information content is <1 at all PAM positions. In some of these cases, there are many mapped spacers and there is a clear PAM on the upstream side while the information content is close to 0 at all positions on the downstream side. I could provide an example like this if helpful.

**Comment by Matteo-Ciciani** [comment]
Yes, that would be great!

**Comment by snayfach** [comment]
See attached for the example. 
[34079.fna.zip](https://github.com/Matteo-Ciciani/PAMpredict/files/11901696/34079.fna.zip)
